config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	validates :country, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(permitted_params.merge(session_id: session.id))
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  private

  def permitted_params
    params.require(:user).permit(:country, :candy_fan, :polish_candy_fan, :night_club_fan, :fan_type, :pierrogi_fan)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HeetchSurvey</title>

    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Heetch users</h1>
 
<table>
  <tr>
    <th>Country</th>
    <th>Pierrogi fan ?</th>
    <th>Candy fan ?</th>
    <th>Polish candy fan ?</th>
    <th>Nightclub fan ?</th>
    <th>Hobby</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.country %></td>
      <td><%= user.pierrogi_fan %></td>
      <td><%= user.candy_fan %></td>
      <td><%= user.polish_candy_fan %></td>
      <td><%= user.night_club_fan %></td>
      <td><%= user.fan_type %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<nav>
  <div class="nav-wrapper red lighten-2">
    <a href="#" class="brand-logo">Heetch</a>
  </div>
</nav>

<p id="notice"><%= notice %></p>

<div id="welcome">
  <h3>Welcome to Heetch survey</h3>
</div>

<%= form_for @user do |f| %>

  <div id="country" class="input-field col s12">
    <%= f.label :country, 'Where are you from ?' %>
    <%= f.text_field :country %>
    <br/>
    <button type="button" class="btn waves-effect waves-light" id="submit_country">Next</button>
  </div>

  <div id="candy" class="hidden col s12" >
    <%= f.check_box :candy_fan %>
    <%= f.label :candy_fan, 'Do you like candy ?' %>
    <br/>
    <br/>
    <button type="button" class="btn waves-effect waves-light" id="submit_candy">Next</button>
  </div>

  <div id="polishcandy" class="hidden col s12" >
    <%= f.check_box :polish_candy_fan %>
    <%= f.label :polish_candy_fan, 'Do you like Polish candy ?' %>
    <br/>
    <br/>
    <button type="button" class="btn waves-effect waves-light" id="submit_polishcandy">Next</button>
  </div>

  <div id="nightclub" class="hidden col s12">
    <%= f.check_box :night_club_fan %>
    <%= f.label :night_club_fan, 'Do you like nightclub ?' %>
    <br/>
    <br/>
    <button type="button" class="btn waves-effect waves-light" id="submit_nightclub">Next</button>
  </div>

  <div id="pierrogi" class="hidden col s12">
    <%= f.check_box :pierrogi_fan %>
    <%= f.label :pierrogi_fan, 'Do you like pierrogi ?' %>
    <br/>
    <br/>
    <button type="button" class="btn waves-effect waves-light" id="submit_pierrogi">Next</button>
  </div>

  <div id="fan" class="hidden input-field col s12">
    <%= f.text_field :fan_type %>
    <%= f.label :fan_type, 'So, what do you like ?' %>
    <br/>
  </div>

  <div id="message" class="hidden" >
   <p>Thanks for following Heetch but we are not open yet in your country :(</p>
  </div>

  <div id="messagepierrogi" class="hidden" >
   <p>Sorry but we don't allow passenger who don't like the pierrogies and candies :/</p>
  </div>
  
  <div id="submit_final" class="hidden">
    <button type="submit" class="btn waves-effect waves-light" id="submit_pierrogi">Submit</button>
  </div>

<% end %>

app/views/users/show.html.erb
<h3>Thanks for using Heetch! </h3>
<h4>Support us #TouchePasAMonHeetch</h4>

<p>
  <strong>Session ID</strong>
  <%= @user.session_id %>
</p>

<p>
  <strong>Country</strong>
  <%= @user.country %>
</p>
 
<p>
  <strong>Candy fan ?</strong>
  <%= @user.candy_fan %>
</p>

<p>
  <strong>Pierrogi fan ?</strong>
  <%= @user.pierrogi_fan %>
</p>

<p>
  <strong>Polish Candy fan ?</strong>
  <%= @user.polish_candy_fan %>
</p>

<p>
  <strong>Nightclub fan ?</strong>
  <%= @user.night_club_fan %>
</p>

<%= link_to "You're not alone, meet others heetch!", users_path %>